"""phase 2: interview extension + interviewer profile, availability windows, slot offers, participants

Revision ID: cf6bd29ccb47
Revises: b5763bd4ab76
Create Date: 2026-09-06 21:07:48.310028

Hand-adjusted from the autogenerated diff (Documentation/CONVENTIONS.md's
"review the generated file" rule) - autogenerate reflects off the *live*
connected DB, and this project's dev.db has several tables never created by
any migration (`interview_requests`, `candidate_availabilities`,
`seat_offers`, `interview_records`, `notification_records`, plus an older
`interviewer_profiles` shape with different columns) - leftovers from before
this schema was migration-tracked. Autogenerate diffed against the *actual*
drifted dev.db, not a clean replay of `init_auth_tables`, and so an
apply-as-generated migration would work on that one drifted file but crash
`alembic upgrade head` from a truly empty DB (no `interviewer_profiles` table
to ALTER, no orphan tables to DROP). This version instead:

* `DROP TABLE IF EXISTS` for every one of those - a no-op on a clean DB,
  harmless cleanup on a drifted one (all confirmed empty - 0 rows - before
  writing this).
* `CREATE TABLE interviewer_profiles` fresh (its "ALTER" in the generated
  version assumed the old orphan shape already existed, which isn't true on
  a clean DB).
* Everything else (the `interviews` extension, the three brand-new tables)
  is an ordinary additive migration, unchanged from what autogenerate
  produced for those parts.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6bd29ccb47'
down_revision: Union[str, None] = 'b5763bd4ab76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_ORPHAN_TABLES = [
    "interview_requests",
    "candidate_availabilities",
    "seat_offers",
    "interview_records",
    "notification_records",
]


def upgrade() -> None:
    # Untracked leftovers from before this schema was migration-managed -
    # see the module docstring. Safe on a clean DB (no-op) and on a drifted
    # one (all confirmed empty).
    op.execute("DROP TABLE IF EXISTS interviewer_profiles")
    for table in _ORPHAN_TABLES:
        op.execute(f"DROP TABLE IF EXISTS {table}")

    op.create_table(
        "interviewer_profiles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("seniority", sa.String(), nullable=False),
        sa.Column("qualified_interview_types", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("working_hours_start", sa.String(), nullable=False),
        sa.Column("working_hours_end", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )

    op.create_table(
        "candidate_availability_windows",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("interview_id", sa.String(), nullable=False),
        sa.Column("start_utc", sa.DateTime(), nullable=False),
        sa.Column("end_utc", sa.DateTime(), nullable=False),
        sa.Column("source_timezone", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("candidate_availability_windows", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_candidate_availability_windows_interview_id"), ["interview_id"], unique=False
        )

    op.create_table(
        "interview_participants",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("interview_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("seat_index", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interview_participants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_interview_participants_interview_id"), ["interview_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_interview_participants_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "interview_slot_offers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("interview_id", sa.String(), nullable=False),
        sa.Column("seat_index", sa.Integer(), nullable=False),
        sa.Column("interviewer_user_id", sa.String(), nullable=False),
        sa.Column("proposed_start_utc", sa.DateTime(), nullable=False),
        sa.Column("proposed_end_utc", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("offered_at", sa.DateTime(), nullable=True),
        sa.Column("responded_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["interview_id"], ["interviews.id"]),
        sa.ForeignKeyConstraint(["interviewer_user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("interview_slot_offers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_interview_slot_offers_interview_id"), ["interview_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_interview_slot_offers_interviewer_user_id"), ["interviewer_user_id"], unique=False
        )

    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by_email", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("interview_type", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("required_skills", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("required_seniority", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("panelists_required", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("hiring_manager_email", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("candidate_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("candidate_email", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("candidate_timezone", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("duration_minutes", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("buffer_minutes_before", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("buffer_minutes_after", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("confirmed_start_utc", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("confirmed_end_utc", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("calendar_event_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("meeting_link", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("seats_json", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("feasibility_json", sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f("ix_interviews_candidate_email"), ["candidate_email"], unique=False)


def downgrade() -> None:
    with op.batch_alter_table("interviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_interviews_candidate_email"))
        batch_op.drop_column("feasibility_json")
        batch_op.drop_column("seats_json")
        batch_op.drop_column("meeting_link")
        batch_op.drop_column("calendar_event_id")
        batch_op.drop_column("confirmed_end_utc")
        batch_op.drop_column("confirmed_start_utc")
        batch_op.drop_column("buffer_minutes_after")
        batch_op.drop_column("buffer_minutes_before")
        batch_op.drop_column("duration_minutes")
        batch_op.drop_column("candidate_timezone")
        batch_op.drop_column("candidate_email")
        batch_op.drop_column("candidate_name")
        batch_op.drop_column("hiring_manager_email")
        batch_op.drop_column("panelists_required")
        batch_op.drop_column("required_seniority")
        batch_op.drop_column("required_skills")
        batch_op.drop_column("interview_type")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_by_email")

    op.drop_table("interview_slot_offers")
    op.drop_table("interview_participants")
    op.drop_table("candidate_availability_windows")
    op.drop_table("interviewer_profiles")
