"""phase 5: reminder_sent_at on interview

Revision ID: e51a316bd556
Revises: cf6bd29ccb47
Create Date: 2026-09-06 23:15:56.362694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51a316bd556'
down_revision: Union[str, None] = 'cf6bd29ccb47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_column('reminder_sent_at')

    # ### end Alembic commands ###
